title: Re-Align Workshop
description: ICLR Workshop on Representational Alignment
url: ""
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

social:
  email: representational-alignment@googlegroups.com

editions:
  - year: 2024
    location: ICLR 2024
  - year: 2025
    location: ICLR 2025
  - year: 2026
    location: ICLR 2026
